In [1]:
import numpy as np

In [5]:
# 理解简单的卷积
x = [6, 2]
h = [1, 2, 5, 4]
y = np.convolve(x, h)
y

# x作为卷积内核，以滑动窗口的形式覆盖h,默认会将内核倒置
# 卷积过程如下：
# 6 = 0x2 + 1x6  #其中0是h左侧填充的数字
# 14 = 1x2 + 2x6
# 34 = 2x2 + 5x6
# 34 = 2x5 + 4x6
# 8 = 4x2 + 0x6

array([ 6, 14, 34, 34,  8])

In [9]:
# 不同形式的卷积
x = [6, 2]
h = [1, 2, 5, 4]

# full是默认的两侧全部填充0
print(np.convolve(x, h, 'full'))
# same只在左侧填充0
print(np.convolve(x, h, 'same'))
# valid则不填充
print(np.convolve(x, h, 'valid'))

[ 6 14 34 34  8]
[ 6 14 34 34]
[14 34 34]


In [10]:
# 使用scipy理解二维卷积
from scipy import signal as sg

# g为卷积内核，默认会将内核旋转180度再进行卷积
I = [[2,4], [11, 22]]
g = [[-1, 1], [2, 3]]

# full为全部填充0
# 第一行-2由[[3,2],[1,-1]]矩阵点乘[[0,0],[0,2]]矩阵再求和得到
# 第二个-2由[[3,2],[1,-1]]矩阵点乘[[0,0],[2,4]]得到
# 其余类推
print(sg.convolve(I, g, 'full'))
# same为左侧和上侧填充0
print(sg.convolve(I, g, 'same'))
# valid为全不填充
print(sg.convolve(I, g, 'valid'))

[[-2 -2  4]
 [-7  3 34]
 [22 77 66]]
[[-2 -2]
 [-7  3]]
[[3]]
