In [6]:
# Tensorflow执行卷积操作时，是以图形的形式创建所有操作
import tensorflow as tf

In [7]:
# 设置输入图层和卷积内核
# 图层和内核数值都由随机数产生，而随机数后面的参数设置了其形状
# input后面[1,3,3,1]表示[批量大小,宽度,高度,通道数目]
# filter后面[2,2,1,1]表示[宽度,高度,通道,滤波器数目]
input = tf.Variable(tf.random_normal([1,3,3,1]))
filter = tf.Variable(tf.random_normal([2,2,1,1]))
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')

In [8]:
# 查看卷积结果
# 原理与二维卷积相同
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

    print("Input \n")
    print('{0} \n'.format(input.eval()))
    print("Filter/Kernel \n")
    print('{0} \n'.format(filter.eval()))
    print("Result/Feature Map with VALID positions \n")
    result = sess.run(op)
print(result)
sess.close()

Input 

[[[[ 1.37472641]
   [-0.72989047]
   [-1.29288471]]

  [[-1.29896688]
   [ 0.27248353]
   [-1.20405543]]

  [[ 1.5457623 ]
   [ 2.18607569]
   [ 2.13252258]]]] 

Filter/Kernel 

[[[[ 1.67247021]]

  [[ 0.21511881]]]


 [[[ 1.24957895]]

  [[-0.39390999]]]] 

Result/Feature Map with VALID positions 

[[[[ 0.41168022]
   [-0.68406475]]

  [[-1.043432  ]
   [ 2.08835793]]]]
