In [1]:
# n维数组ndarray
import numpy as np

In [8]:
# 使用Numpy内部功能函数
a = np.arange(3, 100, 3)
b = np.arange(25).reshape(5, 5)
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
# 使用其他Numpy函数
# 使用zeros函数创建一个填充0的数组
z = np.zeros((2, 4))
# 使用ones函数创建一个填充1的数组
o = np.ones((2, 4))
# 使用empty函数创建一个内容随机的数组(内容取决于当前内存状态)
e = np.empty((2, 4))
# 使用full创建一个给定值的n * n 数组
f = np.full((2, 4), 3)
# 使用eye创建一个对角线为1s，其他为0的数组
ey = np.eye(5, 5)
# 在指定间隔内返回均匀间隔的数字
li = np.linspace(0, 10, 4)
li

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [27]:
# 使用特殊的库函数
r = np.random.random((2, 2))
r

array([[0.52370179, 0.17942129],
       [0.88105877, 0.02286286]])