In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 求和,可指定轴,axis=0表示按列，axis=1表示按轴
arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)
arr.sum(axis=-1)

array([ 6, 15])

In [9]:
# 求最值
arr.min()
arr.max()
arr.min(axis=0)
arr.max(axis=1)

array([3, 6])

In [13]:
# 求最值索引
arr.argmin()
arr.argmax()
arr.argmin(axis=0)
arr.argmax(axis=1)

array([2, 2], dtype=int64)

In [19]:
# 方差
# 方差越小，代表这组数据的离散程度越低
arr.var()
arr.var(axis=0)
arr.var(axis=1)

array([0.66666667, 0.66666667])

In [16]:
# 标准差
# 标准差等于方差开根号
arr.std()
arr.std(axis=0)
arr.std(axis=1)

array([0.81649658, 0.81649658])

In [22]:
# 把数值转化到最小值到最大值之间
# 小于最小值的等于最小值
# 大于最大值的等于最大值
arr.clip(2, 5)

array([[2, 2, 3],
       [4, 5, 5]])

In [24]:
# 四舍五入，可指定精度
a = np.array([1.773, 2.8672, 3.421, 4.289, 5])
a.round(decimals=2)

array([1.77, 2.87, 3.42, 4.29, 5.  ])