In [3]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
arr.shape

(2, 5)

In [5]:
# 行列转置
arr.transpose()
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [9]:
# 数组拼接
a = np.array([[11, 12, 13], [14, 15, 16]])
b = np.array([[21, 22, 23], [24, 25, 26]])
c = np.concatenate((a, b))
c = np.concatenate((a, b), axis = 1)
c

array([[11, 12, 13, 21, 22, 23],
       [14, 15, 16, 24, 25, 26]])

In [11]:
# 按列拼接
np.vstack((a, b))
# 按行拼接
np.hstack((a, b))

array([[11, 12, 13, 21, 22, 23],
       [14, 15, 16, 24, 25, 26]])

In [13]:
# 把数组拉平
arr.flatten()
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])