In [2]:
import numpy as np

In [19]:
# 生成0到1之间的随机数
np.random.random(10)
# 生成2行3列的随机数
np.random.rand(2, 3)

array([[0.00189247, 0.97866778, 0.16432536],
       [0.89380378, 0.25111091, 0.11933986]])

In [17]:
# 随机生成整数
# 生成5个0到10之间的整数，左闭右开
np.random.randint(0, 10, 5)
# 生成2行5列10以内的整数
np.random.randint(10, size=(2, 5))

array([[8, 9, 0, 5, 7],
       [2, 3, 3, 7, 3]])

In [20]:
# 生成符合高斯分布的随机数
# 平均值
avg = 10
# 方差
sigma = 5
np.random.normal(avg, sigma, 10)

array([ 5.21040016,  5.77587601, 16.66612538,  6.63146029, 11.28270093,
        6.20336838,  8.23041668, 12.9595149 ,  0.39509255, 16.93166901])

In [ ]:
# 设置打印小数位
np.set_printoptions(precision = 2)

In [34]:
# 洗牌
# 指定随机种子
# np.random.seed(1)
a = np.arange(10)
np.random.shuffle(a)
a

array([2, 4, 3, 0, 6, 1, 5, 8, 7, 9])